apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gcp-cloudrun-springboot
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
    spec:
      serviceAccountName: gcp-cloudrun-springboot
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: asia.gcr.io/${PROJECT_ID}/springboot:latest
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true